I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 310, in script
    if Milan_choice1Flag is True:
  File "game/script.rpy", line 310, in <module>
    if Milan_choice1Flag is True:
NameError: name 'Milan_choice1Flag' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 310, in script
    if Milan_choice1Flag is True:
  File "D:\Renpy\renpy-6.99.14.1-sdk\renpy\ast.py", line 1702, in execute
    if renpy.python.py_eval(condition):
  File "D:\Renpy\renpy-6.99.14.1-sdk\renpy\python.py", line 1843, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Renpy\renpy-6.99.14.1-sdk\renpy\python.py", line 1836, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 310, in <module>
    if Milan_choice1Flag is True:
NameError: name 'Milan_choice1Flag' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.14.1.3218
hackGSU18 Spring 1.0
Sun Mar 25 08:59:35 2018
